language: java
jdk:
  - oraclejdk8
sudo: false
before_script: cd download-manager
script: mvn clean install package
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "download-runnertarget/downloadrunner-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true
